In [1]:
%run useful_functions.py

C:\Users\natha\Desktop\17-Cyber-risk_and_the_cross-section_of_stock_returns-main (2)\17-Cyber-risk_and_the_cross-section_of_stock_returns-main\Work_Nathan\useful_functions.py:5: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\natha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


update 14


In [2]:
sim_mat=setup_similitude_matrix()

check number of negative similitude : 0


In [3]:
print(sim_mat)
print(sim_mat.shape)

[[1.0000002  0.6542873  0.5804319  ... 0.5044317  0.48481116 0.51478875]
 [0.6542873  0.9999995  0.7706407  ... 0.50514305 0.50925064 0.52966756]
 [0.5804319  0.7706407  1.         ... 0.5064419  0.51968044 0.49092975]
 ...
 [0.5044317  0.50514305 0.5064419  ... 1.0000005  0.9637937  0.67670363]
 [0.48481116 0.50925064 0.51968044 ... 0.9637937  0.9999999  0.69036084]
 [0.51478875 0.52966756 0.49092975 ... 0.67670363 0.69036084 0.99999964]]
(785, 785)


In [4]:
np.savetxt('similitude_matrix.txt', sim_mat, fmt='%.5f')